### PR TITLE
fix(confirm) `--timeout` was ignored, now works as documented

### LINKED ISSUE #698: `confirm` command is ignoring its `--timeout` option
**Describe the bug**

`gum confirm --timeout` never times out despite having a documented `--timeout` option.

Relevant excerpts from `gum confirm --help`

```
Usage: gum confirm [<prompt>] [flags]

Ask a user to confirm an action

Arguments:
  [<prompt>]    Prompt to display.

Flags:
     --default              Default confirmation action
     --timeout=0            Timeout until confirm returns selected value or default if provided ($GUM_CONFIRM_TIMEOUT)
```

**To Reproduce**

This never times out:
```console
❯ gum confirm --timeout=1s && echo "timed out"
```

Repro but it's a `.tape` file:
```vhs
Set TypingSpeed 0.1
Output broken-main.gif
Set Shell zsh
Sleep 500ms
Type "git checkout main && git fetch upstream main && git rev-parse HEAD"
Enter
Type "date +%H:%M:%S.%1N && go run . confirm --timeout=1s --default='Yes' && echo 'Success'"
Enter
Sleep 4s
Ctrl+C
Type "date +%H:%M:%S.%1N"
Enter
Sleep 4s
Ctrl+D
```

**Expected behavior**
Confirm times out after the specified duration as described in the docs.

```console
❯ ./gum confirm --timeout=1s && echo "timed out"
┃  Are you sure?
┃
┃     Yes        No

timed out
```

**Screenshots**

### Before

Gum timeout wrapped in an external `timeout` command. See that it does not stop at 1 second but stops at 5 per the wrapping command:

image

### After (using fix from #697)

Same call as before but gum times out at 1 second as expected:

image

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser: uhh.. `alacritty` is my terminal emulator, `fish` my shell
 - Version: MacOS 15.0.1 (24A348)

**Additional context**

I have a unit tested fix up in #697.

### PR DESCRIPTION
**Pull request by dpritchett**
Fixes #698.

Relevant excerpts from `gum confirm --help`

```console
Usage: gum confirm [<prompt>] [flags]

Ask a user to confirm an action

Arguments:
  [<prompt>]    Prompt to display.

Flags:
     --default              Default confirmation action
     --timeout=0            Timeout until confirm returns selected value or default if provided ($GUM_CONFIRM_TIMEOUT)
```

## Changes
- Chains a `.WithTimeout(o.Timeout)` in the `confirm` command's `huh.NewForm()` chain under `confirm.Run()`
- Adds an `errIsValidTimeout(error) bool` method to `confirm.Options` to facilitate safely ignoring the timeout error returned in the course of the `Run()` context expiring due to timeout
- Adds unit tests for `errIsValidTimeout`

#### Before: doesn't time out without outside help

Made with VHS

Note that five seconds elapse here before `timeout` kills `gum`, returning a nonzero exit code.

```vhs
Set TypingSpeed 0.1
Output broken-main.gif
Set Shell zsh
Sleep 500ms
Type "git checkout main && git fetch upstream main && git rev-parse HEAD"
Enter
Type "date +%H:%M:%S.%1N && go run . confirm --timeout=1s --default='Yes' && echo 'Success'"
Enter
Sleep 4s
Ctrl+C
Type "date +%H:%M:%S.%1N"
Enter
Sleep 4s
Ctrl+D
```

#### After: times out as expected

Made with VHS

Times out in ~1 second as desired.

```vhs
Output fixed.gif
Set Shell zsh
Sleep 500ms
Type "git checkout bug-confirm-timeout-was-missing && git rev-parse HEAD"
Enter
Sleep 1.5s
Type "go run . confirm --timeout=1s 'Am I going to time out?' --default='Yes' && echo Success"
Enter
Sleep 3s
Ctrl+D
```

Also works with `GUM_CONFIRM_TIMEOUT`.

### CODE REVIEW

File: confirm/command.go [hunk 1]
```diff
@@ -40,3 +45,11 @@ func (o Options) Run() error {
 
 	return nil
 }
+
+// errIsValidTimeout returns false unless 1) the user has specified a nonzero timeout and 2) the error is a huh.ErrTimeout.
+func (o Options) errIsValidTimeout(err error) bool {
+	errWasTimeout := err.Error() == huh.ErrTimeout.Error()
```
Comment (caarlos0) [inline confirm/command.go:51]:
```suggestion
	errWasTimeout := errors.Is(err, huh.ErrTimeout)
```

File: confirm/command.go [hunk 2]
```diff
@@ -26,12 +26,17 @@ func (o Options) Run() error {
...
+		WithTimeout(o.Timeout).
 		WithTheme(theme).
 		WithShowHelp(o.ShowHelp).
 		Run()
 
 	if err != nil {
-		return fmt.Errorf("unable to run confirm: %w", err)
+		allowErr := o.errIsValidTimeout(err)
+
+		if !allowErr {
```
Comment (caarlos0) [inline confirm/command.go:37]:
```suggestion
		if !o.errIsValidTimeout(err) {
```

**Review by caarlos0 — APPROVED** [review]
just a couple of small things, looks good otherwise

thank so much for the PR!

**Comment by dpritchett** [comment]
> just a couple of small things, looks good otherwise
> 
> thank so much for the PR!

Nice suggestions, thanks. I've added them.

**Comment by caarlos0** [comment]
thanks!
